Iter4
anoriar/gophkeeper pull request #1
Opened 2024-03-11 14:16 UTC by anoriar

2024-03-12 08:25 UTC, gonozov0 requested changes
Отличная работа 👍
Отдельный респект за swagger и readme
Из обязательных доработок остались тесты. Хотя бы на core функциональность с синхронизацией
Из желаемых еще можно прикрутить сохранение произвольных текстовых и бинарных данных

2024-03-12 08:25 UTC, gonozov0 commented on .idea/runConfigurations/client_login.xml
.idea стоит добавить в .gitignore и удалить через `git rm -r --cached .idea`

2024-03-12 08:25 UTC, gonozov0 commented on internal/client/entry/dto/command/add_entry_command.go
Немного мыслей по архитектуре кода
Ты выстроил архитектуру кода внутри entry, группируя код по его принадлежности к категории:
Отдельно разбиты по модулям:
- структуры и модели (dto)
- фабрики
- репозитории
- сервисы

На мой взгляд более гибкий, расширяемый и самое главное читабельный вариант - это группировка по бизнес функциональности. В данном модуле это примерно разбивка на:
- add_login
- add_card
- и т.д.

Уже внутри этой бизнес функциональности будут нужные dto, интерфейсы и репозитории для отправки этих нужных данных на сервер

Естественно переделывать ничего не нужно, ты уже написал много рабочего кода, просто мысли вслух.
Сейчас довольно много файлов, и в процессе понимания кода все их сложно логически уложить и перегруппировать в голове

2024-03-17 14:55 UTC, anoriar commented on .idea/runConfigurations/client_login.xml
я это специально оставил, чтобы было удобно работать с командной строкой

руками вводить каждый раз команды - долгий вариант

а тут сохраняю в runConfigurations нужные команды и они не потеряются в ide

2024-03-18 13:55 UTC, merged